title:            Tanf
description:      当你的才华还撑不起你的野心时，你就应该静下心来学习。
url:              # Site url.
baseurl:          http://tandaly.github.com/blog
year:               2014
signoff:          Tanf # Your name.
disqus_shortname: tandalygithub # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         Blog
    url:          http://tandaly.github.io
  - name:         Course
    url:          http://tandaly.github.io/course
    external:     true
  - name:         Game
    url:          /blog/games
  - name:         Video
    url:          /blog/video
    external:     true
  - name:         Pages
    url:          /pages/
    external:     true
  - name:         Tools
    url:          http://tools.dedecms.com/
    external:     true
  - name:         Google-ips
    url:          http://tandaly.github.io/test/ip.html
    external:     true
  - name:         Links
    url:          /blog/links
  - name:         About
    url:          /blog/about

pygments:         true
#permalink:        pretty
permalink:        /:year/:month/:day/:title.html
# 当修改文件时重新生成站点
auto:             true
markdown:         redcarpet
#markdown:         kramdown
redcarpet:
  extensions:     [autolink, tables]
